name: flex_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  bloc: ^8.1.0
  circular_indicator: ^1.0.6
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^9.9.1
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  sliding_up_panel: ^2.0.0+1
  chewie: ^1.3.5
  video_player: ^2.4.7
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.9
  permission_handler: ^10.0.1
  timezone: ^0.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #